### ISSUE TITLE
Connect github repo to trello board

### ISSUE THREAD

**Issue by HamiltonChris** [SFU-Embedded-Cosplay/Halo-Suit-BeagleBone#2]
Zapier (zapier.com/zapbook/github/trello/) has a plugin that can integrate github and Trello.

**Comment by HamiltonChris** [comment]
It turns out that Zapier isn't free so that may not be the best option.

**Comment by Tyler-R** [comment]
This should be addressed with Adam's code that synces Trello and Github issues.  The code can be found here https://github.com/abrykajlo/trellhub
