### ISSUE TITLE
Beaglebone USB failing

### ISSUE THREAD

**Issue by HamiltonChris** [SFU-Embedded-Cosplay/Halo-Suit-BeagleBone#23]
Beaglebone's usb sometimes fails on startup preventing ssh. Sometimes it works and sometimes it doesn't. We recently reflashed the beaglebone but it doesn't fix the problem. We may need to use a new beaglebone but it will do for now.

**Comment by Tyler-R** [comment]
I believe this was handled earlier in the semester and is no longer relevant.
