### ISSUE TITLE
Add the ability to remove automation on compilation

### ISSUE THREAD

**Issue by HamiltonChris** [SFU-Embedded-Cosplay/Halo-Suit-BeagleBone#25]
Since automation often makes demos not look very good we need the ability to remove it on compilation so that we can just demo bluetooth communication.

**Comment by Tyler-R** [comment]
This command was added in commit 9734f43ccec976d9ddd545e02920435a3076e347.  Compiling without automation can now be done with the command:

```
$ make noauto
```
