### ISSUE TITLE
Some error inside set_bluetooth_mode is not being handled

### ISSUE THREAD

**Issue by HamiltonChris** [SFU-Embedded-Cosplay/Halo-Suit-BeagleBone#27]
When the bluetooth dongle isn't recognised (in this case because of a lack of power) the program crashes. We suspect it's some error that wasn't been handled.

**Comment by Tyler-R** [comment]
I rediscovered this bug and made and created issue #35 addressing this issue.  We should make finding a fix for this a high priority.
