### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by HamiltonChris** [SFU-Embedded-Cosplay/Halo-Suit-BeagleBone#7]
There is some extra stuff in this repo that needs removing since it's no longer needed.
TODO:
- [x] automationtestdata.c is some old test code that no longer works nor is supported by the project
- [x] the depricated folder is no longer relevant to the project and should be removed.

**Comment by Tyler-R** [comment]
The deprecated folder was removed in 694fabf55931790aa55ed22fcb8efe4a13b53d51.

**Comment by Tyler-R** [comment]
I'm closing this under the assumption that the pull request will go smoothly.
